version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis-vol:/data
  web-app:
    image: aggonzalez97/cloud9-image
    container_name: latest
    ports:
      - "80:80"
    depends_on:
      - redis
volumes:
  redis-vol:
    name: redis-vol